spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: NOTTORI5817wwms

  sql:
    init:
      mode: always

server:
  port: 8008
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true   