spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: app
    password: app

  sql:
    init:
      mode: always

server:
  port: 8008
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true  
    
jwt:
  secret: secret_key
  expiration: 86400000  # 有効期限: 1日 (ミリ秒)

schema:
  type: object  