DROP TABLE IF EXISTS todo;
DROP TABLE IF EXISTS users;

CREATE TABLE todo (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    details TEXT
);

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
	email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);